# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(1000, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1000, 720))
        Dialog.setMaximumSize(QtCore.QSize(100000, 100000))
        Dialog.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.window_title = QtWidgets.QLabel(Dialog)
        self.window_title.setMinimumSize(QtCore.QSize(600, 35))
        self.window_title.setMaximumSize(QtCore.QSize(600, 35))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.window_title.setFont(font)
        self.window_title.setObjectName("window_title")
        self.verticalLayout_4.addWidget(self.window_title)
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setMinimumSize(QtCore.QSize(650, 0))
        self.line_5.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.display = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setMinimumSize(QtCore.QSize(600, 400))
        self.display.setMaximumSize(QtCore.QSize(2000, 500))
        self.display.setText("")
        self.display.setObjectName("display")
        self.verticalLayout_4.addWidget(self.display)
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setMinimumSize(QtCore.QSize(650, 0))
        self.line_6.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.textBrowser_terminal = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_terminal.setMinimumSize(QtCore.QSize(650, 120))
        self.textBrowser_terminal.setMaximumSize(QtCore.QSize(2000, 600))
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.verticalLayout_4.addWidget(self.textBrowser_terminal)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(200, 28))
        self.label.setMaximumSize(QtCore.QSize(400, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(85, 20))
        self.label_7.setMaximumSize(QtCore.QSize(85, 24))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lineEdit_batchSize = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_batchSize.sizePolicy().hasHeightForWidth())
        self.lineEdit_batchSize.setSizePolicy(sizePolicy)
        self.lineEdit_batchSize.setMinimumSize(QtCore.QSize(30, 20))
        self.lineEdit_batchSize.setMaximumSize(QtCore.QSize(310, 24))
        self.lineEdit_batchSize.setObjectName("lineEdit_batchSize")
        self.horizontalLayout_3.addWidget(self.lineEdit_batchSize)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(85, 20))
        self.label_9.setMaximumSize(QtCore.QSize(85, 24))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.lineEdit_trainConfig = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_trainConfig.sizePolicy().hasHeightForWidth())
        self.lineEdit_trainConfig.setSizePolicy(sizePolicy)
        self.lineEdit_trainConfig.setMinimumSize(QtCore.QSize(30, 20))
        self.lineEdit_trainConfig.setMaximumSize(QtCore.QSize(310, 24))
        self.lineEdit_trainConfig.setObjectName("lineEdit_trainConfig")
        self.horizontalLayout_4.addWidget(self.lineEdit_trainConfig)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton_train = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_train.sizePolicy().hasHeightForWidth())
        self.pushButton_train.setSizePolicy(sizePolicy)
        self.pushButton_train.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_train.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_train.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_train.setAutoDefault(False)
        self.pushButton_train.setObjectName("pushButton_train")
        self.verticalLayout.addWidget(self.pushButton_train)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(200, 28))
        self.label_2.setMaximumSize(QtCore.QSize(400, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(100, 20))
        self.label_6.setMaximumSize(QtCore.QSize(100, 24))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_scoreThreshold = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_scoreThreshold.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit_scoreThreshold.setMaximumSize(QtCore.QSize(40, 24))
        self.lineEdit_scoreThreshold.setDragEnabled(False)
        self.lineEdit_scoreThreshold.setObjectName("lineEdit_scoreThreshold")
        self.horizontalLayout.addWidget(self.lineEdit_scoreThreshold)
        self.horizontalSlider_scoreThreshold = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_scoreThreshold.setMinimumSize(QtCore.QSize(50, 20))
        self.horizontalSlider_scoreThreshold.setMaximumSize(QtCore.QSize(200, 24))
        self.horizontalSlider_scoreThreshold.setMaximum(99)
        self.horizontalSlider_scoreThreshold.setProperty("value", 15)
        self.horizontalSlider_scoreThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scoreThreshold.setObjectName("horizontalSlider_scoreThreshold")
        self.horizontalLayout.addWidget(self.horizontalSlider_scoreThreshold)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.radioButton_batchEvaluation = QtWidgets.QRadioButton(Dialog)
        self.radioButton_batchEvaluation.setEnabled(True)
        self.radioButton_batchEvaluation.setMaximumSize(QtCore.QSize(400, 16777215))
        self.radioButton_batchEvaluation.setAutoRepeat(True)
        self.radioButton_batchEvaluation.setAutoExclusive(False)
        self.radioButton_batchEvaluation.setObjectName("radioButton_batchEvaluation")
        self.verticalLayout.addWidget(self.radioButton_batchEvaluation)
        self.pushButton_selectModel = QtWidgets.QPushButton(Dialog)
        self.pushButton_selectModel.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_selectModel.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_selectModel.setAutoDefault(False)
        self.pushButton_selectModel.setObjectName("pushButton_selectModel")
        self.verticalLayout.addWidget(self.pushButton_selectModel)
        self.pushButton_selectImage = QtWidgets.QPushButton(Dialog)
        self.pushButton_selectImage.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_selectImage.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_selectImage.setAutoDefault(False)
        self.pushButton_selectImage.setObjectName("pushButton_selectImage")
        self.verticalLayout.addWidget(self.pushButton_selectImage)
        self.pushButton_evaluate = QtWidgets.QPushButton(Dialog)
        self.pushButton_evaluate.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_evaluate.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_evaluate.setAutoDefault(False)
        self.pushButton_evaluate.setObjectName("pushButton_evaluate")
        self.verticalLayout.addWidget(self.pushButton_evaluate)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(200, 28))
        self.label_3.setMaximumSize(QtCore.QSize(400, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(100, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 24))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.lineEdit_numImage = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_numImage.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit_numImage.setMaximumSize(QtCore.QSize(50, 24))
        self.lineEdit_numImage.setDragEnabled(False)
        self.lineEdit_numImage.setObjectName("lineEdit_numImage")
        self.horizontalLayout_2.addWidget(self.lineEdit_numImage)
        self.horizontalSlider_numImage = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_numImage.setMinimumSize(QtCore.QSize(50, 20))
        self.horizontalSlider_numImage.setMaximumSize(QtCore.QSize(200, 24))
        self.horizontalSlider_numImage.setMinimum(100)
        self.horizontalSlider_numImage.setMaximum(10000)
        self.horizontalSlider_numImage.setProperty("value", 1000)
        self.horizontalSlider_numImage.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_numImage.setObjectName("horizontalSlider_numImage")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_numImage)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_selectModel_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_selectModel_2.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_selectModel_2.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_selectModel_2.setAutoDefault(False)
        self.pushButton_selectModel_2.setObjectName("pushButton_selectModel_2")
        self.verticalLayout.addWidget(self.pushButton_selectModel_2)
        self.pushButton_benchmark = QtWidgets.QPushButton(Dialog)
        self.pushButton_benchmark.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_benchmark.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_benchmark.setAutoDefault(False)
        self.pushButton_benchmark.setObjectName("pushButton_benchmark")
        self.verticalLayout.addWidget(self.pushButton_benchmark)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(200, 28))
        self.label_4.setMaximumSize(QtCore.QSize(400, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMinimumSize(QtCore.QSize(100, 20))
        self.label_10.setMaximumSize(QtCore.QSize(100, 24))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.lineEdit_onlineThreshold = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_onlineThreshold.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit_onlineThreshold.setMaximumSize(QtCore.QSize(50, 24))
        self.lineEdit_onlineThreshold.setObjectName("lineEdit_onlineThreshold")
        self.horizontalLayout_6.addWidget(self.lineEdit_onlineThreshold)
        self.radioButton_webcam = QtWidgets.QRadioButton(Dialog)
        self.radioButton_webcam.setMinimumSize(QtCore.QSize(75, 20))
        self.radioButton_webcam.setMaximumSize(QtCore.QSize(75, 20))
        self.radioButton_webcam.setCheckable(True)
        self.radioButton_webcam.setAutoRepeat(True)
        self.radioButton_webcam.setAutoExclusive(False)
        self.radioButton_webcam.setObjectName("radioButton_webcam")
        self.horizontalLayout_6.addWidget(self.radioButton_webcam)
        self.lineEdit_camIndex = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_camIndex.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit_camIndex.setMaximumSize(QtCore.QSize(50, 24))
        self.lineEdit_camIndex.setObjectName("lineEdit_camIndex")
        self.horizontalLayout_6.addWidget(self.lineEdit_camIndex)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButton_onlineModel = QtWidgets.QPushButton(Dialog)
        self.pushButton_onlineModel.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_onlineModel.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_onlineModel.setAutoDefault(True)
        self.pushButton_onlineModel.setObjectName("pushButton_onlineModel")
        self.verticalLayout.addWidget(self.pushButton_onlineModel)
        self.pushButton_onlineVideo = QtWidgets.QPushButton(Dialog)
        self.pushButton_onlineVideo.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_onlineVideo.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_onlineVideo.setAutoDefault(True)
        self.pushButton_onlineVideo.setObjectName("pushButton_onlineVideo")
        self.verticalLayout.addWidget(self.pushButton_onlineVideo)
        self.pushButton_onlineTest = QtWidgets.QPushButton(Dialog)
        self.pushButton_onlineTest.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_onlineTest.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_onlineTest.setAutoDefault(True)
        self.pushButton_onlineTest.setObjectName("pushButton_onlineTest")
        self.verticalLayout.addWidget(self.pushButton_onlineTest)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(200, 28))
        self.label_5.setMaximumSize(QtCore.QSize(400, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.pushButton_reset = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reset.sizePolicy().hasHeightForWidth())
        self.pushButton_reset.setSizePolicy(sizePolicy)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_reset.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_reset.setAutoDefault(True)
        self.pushButton_reset.setDefault(True)
        self.pushButton_reset.setFlat(False)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout.addWidget(self.pushButton_reset)
        self.pushButton_clearTerminal = QtWidgets.QPushButton(Dialog)
        self.pushButton_clearTerminal.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_clearTerminal.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_clearTerminal.setSizeIncrement(QtCore.QSize(0, 24))
        self.pushButton_clearTerminal.setAutoDefault(False)
        self.pushButton_clearTerminal.setObjectName("pushButton_clearTerminal")
        self.verticalLayout.addWidget(self.pushButton_clearTerminal)
        self.pushButton_terminateThread = QtWidgets.QPushButton(Dialog)
        self.pushButton_terminateThread.setMinimumSize(QtCore.QSize(200, 20))
        self.pushButton_terminateThread.setMaximumSize(QtCore.QSize(400, 32))
        self.pushButton_terminateThread.setSizeIncrement(QtCore.QSize(0, 24))
        self.pushButton_terminateThread.setAutoDefault(False)
        self.pushButton_terminateThread.setDefault(False)
        self.pushButton_terminateThread.setFlat(False)
        self.pushButton_terminateThread.setObjectName("pushButton_terminateThread")
        self.verticalLayout.addWidget(self.pushButton_terminateThread)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.window_title.setText(_translate("Dialog", "YOLACT - GUI"))
        self.label.setText(_translate("Dialog", "Training"))
        self.label_7.setText(_translate("Dialog", "Batch size: "))
        self.lineEdit_batchSize.setText(_translate("Dialog", "1"))
        self.label_9.setText(_translate("Dialog", "Config object:"))
        self.lineEdit_trainConfig.setText(_translate("Dialog", "yolact_base_config"))
        self.pushButton_train.setText(_translate("Dialog", "Train"))
        self.label_2.setText(_translate("Dialog", "Evaluation"))
        self.label_6.setText(_translate("Dialog", "Score Threshold: "))
        self.lineEdit_scoreThreshold.setText(_translate("Dialog", "0.15"))
        self.radioButton_batchEvaluation.setText(_translate("Dialog", "Batch evaluation"))
        self.pushButton_selectModel.setText(_translate("Dialog", "Select model"))
        self.pushButton_selectImage.setText(_translate("Dialog", "Select image"))
        self.pushButton_evaluate.setText(_translate("Dialog", "Evaluate"))
        self.label_3.setText(_translate("Dialog", "Benchmark on COCO"))
        self.label_8.setText(_translate("Dialog", "Num. of images: "))
        self.lineEdit_numImage.setText(_translate("Dialog", "1000"))
        self.pushButton_selectModel_2.setText(_translate("Dialog", "Select model"))
        self.pushButton_benchmark.setText(_translate("Dialog", "Start"))
        self.label_4.setText(_translate("Dialog", "Online Test"))
        self.label_10.setText(_translate("Dialog", "Score Threshold: "))
        self.lineEdit_onlineThreshold.setText(_translate("Dialog", "0.15"))
        self.radioButton_webcam.setText(_translate("Dialog", "Webcam"))
        self.lineEdit_camIndex.setText(_translate("Dialog", "0"))
        self.pushButton_onlineModel.setText(_translate("Dialog", "Select model"))
        self.pushButton_onlineVideo.setText(_translate("Dialog", "Select video"))
        self.pushButton_onlineTest.setText(_translate("Dialog", "Online Test"))
        self.label_5.setText(_translate("Dialog", "Reset"))
        self.pushButton_reset.setText(_translate("Dialog", "Reset"))
        self.pushButton_clearTerminal.setText(_translate("Dialog", "Clear Terminal"))
        self.pushButton_terminateThread.setText(_translate("Dialog", "Stop"))

