# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1100, 800))
        Dialog.setMaximumSize(QtCore.QSize(1100, 800))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(680, 70, 411, 718))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_mainMenu = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_mainMenu.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_mainMenu.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_mainMenu.setObjectName("verticalLayout_mainMenu")
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_mainMenu.addWidget(self.line_7)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(200, 32))
        self.label.setMaximumSize(QtCore.QSize(2000, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_mainMenu.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(85, 24))
        self.label_7.setMaximumSize(QtCore.QSize(85, 24))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lineEdit_batchSize = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_batchSize.setMinimumSize(QtCore.QSize(30, 24))
        self.lineEdit_batchSize.setMaximumSize(QtCore.QSize(3000, 24))
        self.lineEdit_batchSize.setObjectName("lineEdit_batchSize")
        self.horizontalLayout_3.addWidget(self.lineEdit_batchSize)
        self.verticalLayout_mainMenu.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(85, 0))
        self.label_9.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.lineEdit_trainConfig = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_trainConfig.setMinimumSize(QtCore.QSize(30, 24))
        self.lineEdit_trainConfig.setMaximumSize(QtCore.QSize(3000, 24))
        self.lineEdit_trainConfig.setObjectName("lineEdit_trainConfig")
        self.horizontalLayout_4.addWidget(self.lineEdit_trainConfig)
        self.verticalLayout_mainMenu.addLayout(self.horizontalLayout_4)
        self.pushButton_train = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_train.sizePolicy().hasHeightForWidth())
        self.pushButton_train.setSizePolicy(sizePolicy)
        self.pushButton_train.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_train.setMaximumSize(QtCore.QSize(2000, 32))
        self.pushButton_train.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_train.setObjectName("pushButton_train")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_train)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_mainMenu.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 32))
        self.label_2.setMaximumSize(QtCore.QSize(2000, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_mainMenu.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(100, 24))
        self.label_6.setMaximumSize(QtCore.QSize(100, 24))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_scoreThreshold = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_scoreThreshold.setMinimumSize(QtCore.QSize(40, 24))
        self.lineEdit_scoreThreshold.setMaximumSize(QtCore.QSize(40, 24))
        self.lineEdit_scoreThreshold.setDragEnabled(False)
        self.lineEdit_scoreThreshold.setObjectName("lineEdit_scoreThreshold")
        self.horizontalLayout.addWidget(self.lineEdit_scoreThreshold)
        self.horizontalSlider_scoreThreshold = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_scoreThreshold.setMinimumSize(QtCore.QSize(150, 24))
        self.horizontalSlider_scoreThreshold.setMaximumSize(QtCore.QSize(300, 24))
        self.horizontalSlider_scoreThreshold.setMaximum(99)
        self.horizontalSlider_scoreThreshold.setProperty("value", 15)
        self.horizontalSlider_scoreThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scoreThreshold.setObjectName("horizontalSlider_scoreThreshold")
        self.horizontalLayout.addWidget(self.horizontalSlider_scoreThreshold)
        self.verticalLayout_mainMenu.addLayout(self.horizontalLayout)
        self.radioButton_batchEvaluation = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_batchEvaluation.setObjectName("radioButton_batchEvaluation")
        self.verticalLayout_mainMenu.addWidget(self.radioButton_batchEvaluation)
        self.pushButton_selectModel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_selectModel.setMinimumSize(QtCore.QSize(200, 24))
        self.pushButton_selectModel.setMaximumSize(QtCore.QSize(2000, 24))
        self.pushButton_selectModel.setObjectName("pushButton_selectModel")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_selectModel)
        self.pushButton_selectImage = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_selectImage.setMinimumSize(QtCore.QSize(200, 24))
        self.pushButton_selectImage.setMaximumSize(QtCore.QSize(2000, 24))
        self.pushButton_selectImage.setObjectName("pushButton_selectImage")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_selectImage)
        self.pushButton_evaluate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_evaluate.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_evaluate.setMaximumSize(QtCore.QSize(20000, 32))
        self.pushButton_evaluate.setObjectName("pushButton_evaluate")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_evaluate)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_mainMenu.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(200, 32))
        self.label_3.setMaximumSize(QtCore.QSize(2000, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_mainMenu.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(100, 24))
        self.label_8.setMaximumSize(QtCore.QSize(100, 24))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.lineEdit_numImage = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_numImage.setMinimumSize(QtCore.QSize(50, 24))
        self.lineEdit_numImage.setMaximumSize(QtCore.QSize(50, 24))
        self.lineEdit_numImage.setDragEnabled(False)
        self.lineEdit_numImage.setObjectName("lineEdit_numImage")
        self.horizontalLayout_2.addWidget(self.lineEdit_numImage)
        self.horizontalSlider_numImage = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_numImage.setMinimumSize(QtCore.QSize(150, 24))
        self.horizontalSlider_numImage.setMaximumSize(QtCore.QSize(300, 24))
        self.horizontalSlider_numImage.setMinimum(100)
        self.horizontalSlider_numImage.setMaximum(10000)
        self.horizontalSlider_numImage.setProperty("value", 1000)
        self.horizontalSlider_numImage.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_numImage.setObjectName("horizontalSlider_numImage")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_numImage)
        self.verticalLayout_mainMenu.addLayout(self.horizontalLayout_2)
        self.pushButton_selectModel_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_selectModel_2.setMinimumSize(QtCore.QSize(200, 24))
        self.pushButton_selectModel_2.setMaximumSize(QtCore.QSize(2000, 24))
        self.pushButton_selectModel_2.setObjectName("pushButton_selectModel_2")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_selectModel_2)
        self.pushButton_benchmark = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_benchmark.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_benchmark.setMaximumSize(QtCore.QSize(2000, 32))
        self.pushButton_benchmark.setObjectName("pushButton_benchmark")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_benchmark)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_mainMenu.addWidget(self.line_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(200, 32))
        self.label_4.setMaximumSize(QtCore.QSize(2000, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_mainMenu.addWidget(self.label_4)
        self.pushButton_onlineTest = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_onlineTest.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_onlineTest.setMaximumSize(QtCore.QSize(2000, 32))
        self.pushButton_onlineTest.setObjectName("pushButton_onlineTest")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_onlineTest)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_mainMenu.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(200, 32))
        self.label_5.setMaximumSize(QtCore.QSize(2000, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_mainMenu.addWidget(self.label_5)
        self.pushButton_reset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(200, 24))
        self.pushButton_reset.setMaximumSize(QtCore.QSize(2000, 24))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_reset)
        self.pushButton_clearTerminal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_clearTerminal.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_clearTerminal.setSizeIncrement(QtCore.QSize(0, 24))
        self.pushButton_clearTerminal.setObjectName("pushButton_clearTerminal")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_clearTerminal)
        self.pushButton_terminateThread = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_terminateThread.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_terminateThread.setSizeIncrement(QtCore.QSize(0, 24))
        self.pushButton_terminateThread.setDefault(False)
        self.pushButton_terminateThread.setFlat(False)
        self.pushButton_terminateThread.setObjectName("pushButton_terminateThread")
        self.verticalLayout_mainMenu.addWidget(self.pushButton_terminateThread)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 661, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.window_title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.window_title.setMinimumSize(QtCore.QSize(600, 35))
        self.window_title.setMaximumSize(QtCore.QSize(600, 35))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.window_title.setFont(font)
        self.window_title.setObjectName("window_title")
        self.verticalLayout_4.addWidget(self.window_title)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setMinimumSize(QtCore.QSize(650, 0))
        self.line_5.setMaximumSize(QtCore.QSize(650, 16777215))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.display = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.display.setMinimumSize(QtCore.QSize(600, 500))
        self.display.setMaximumSize(QtCore.QSize(600, 500))
        self.display.setText("")
        self.display.setObjectName("display")
        self.verticalLayout_4.addWidget(self.display)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_6.setMinimumSize(QtCore.QSize(650, 0))
        self.line_6.setMaximumSize(QtCore.QSize(650, 16777215))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.textBrowser_terminal = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_terminal.setGeometry(QtCore.QRect(10, 640, 661, 151))
        self.textBrowser_terminal.setMinimumSize(QtCore.QSize(600, 120))
        self.textBrowser_terminal.setMaximumSize(QtCore.QSize(160000, 600))
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Training"))
        self.label_7.setText(_translate("Dialog", "Batch size: "))
        self.lineEdit_batchSize.setText(_translate("Dialog", "1"))
        self.label_9.setText(_translate("Dialog", "Config object:"))
        self.lineEdit_trainConfig.setText(_translate("Dialog", "yolact_base_config"))
        self.pushButton_train.setText(_translate("Dialog", "Train"))
        self.label_2.setText(_translate("Dialog", "Evaluation"))
        self.label_6.setText(_translate("Dialog", "Score Threshold: "))
        self.lineEdit_scoreThreshold.setText(_translate("Dialog", "0.15"))
        self.radioButton_batchEvaluation.setText(_translate("Dialog", "Batch evaluation"))
        self.pushButton_selectModel.setText(_translate("Dialog", "Select model"))
        self.pushButton_selectImage.setText(_translate("Dialog", "Select image"))
        self.pushButton_evaluate.setText(_translate("Dialog", "Evaluate"))
        self.label_3.setText(_translate("Dialog", "Benchmark on COCO"))
        self.label_8.setText(_translate("Dialog", "Num. of images: "))
        self.lineEdit_numImage.setText(_translate("Dialog", "1000"))
        self.pushButton_selectModel_2.setText(_translate("Dialog", "Select model"))
        self.pushButton_benchmark.setText(_translate("Dialog", "Start"))
        self.label_4.setText(_translate("Dialog", "Online Test"))
        self.pushButton_onlineTest.setText(_translate("Dialog", "Online Test"))
        self.label_5.setText(_translate("Dialog", "Reset"))
        self.pushButton_reset.setText(_translate("Dialog", "Reset"))
        self.pushButton_clearTerminal.setText(_translate("Dialog", "Clear Terminal"))
        self.pushButton_terminateThread.setText(_translate("Dialog", "Stop"))
        self.window_title.setText(_translate("Dialog", "YOLACT - GUI"))

